/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.MainMenuCntl;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import Models.CourseNode;
import Models.ProjectNode;

/**
 *
 * @author Charles
 */
public class RunSetupUI extends javax.swing.JFrame {

    /**
     * Creates new form SpecifyRunParameters
     */
    
        
    private DefaultListModel listModel;
    private MainMenuCntl theMainMenuCntl;
    private ArrayList<Object> listToPass;
    private CourseNode theCourseNode;
    private ProjectNode theProjectNode;
    
    public RunSetupUI(MainMenuCntl theParentMainMenuCntl, JTree theCourseTree) {
        
        theMainMenuCntl = theParentMainMenuCntl;
        initComponents();
        listToPass = new ArrayList();
        listModel = new DefaultListModel();
        projectRunList.setModel(listModel);
        courseTree.setModel(theCourseTree.getModel());
        
        this.setVisible(true);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        runSetupLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectRunList = new javax.swing.JList();
        projectRunLabel = new javax.swing.JLabel();
        RemoveBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        projectComboBox = new javax.swing.JComboBox();
        bottomPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        RunBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        runSetupLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        runSetupLabel.setText("Run Setup");

        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        courseTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(courseTree);

        projectRunList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Student 1 Project 1", "Student 1 Project 2", "Student 1 Project 3", "Student 1 Project 4", "Student 1 Project 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        projectRunList.setToolTipText("");
        jScrollPane2.setViewportView(projectRunList);

        projectRunLabel.setText("Projects to Run");

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Project 1", "Project 2", "Project 3", "Project 4" }));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(projectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectRunLabel)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(RemoveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBtn)
                            .addComponent(RemoveBtn)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(projectRunLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        RunBtn.setText("Run");
        RunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(RunBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(RunBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runSetupLabel)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runSetupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:        
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                           courseTree.getLastSelectedPathComponent();
        
        System.out.println("You are adding a " + node.getClass().toString());
        
       
        
        //Object nodeInfo = node.getUserObject();
        /*if (node == null) return;
        else{
            listModel.addElement(nodeInfo);
        }*/
        if (node == null) return;
        
        
        else if(node instanceof ProjectNode){
            listModel.addElement(node);
        }
        else if(node instanceof CourseNode){
            //Pull list of project types from ProjectComboBox   
            theCourseNode.setUserObject(node);
            String value = projectComboBox.getSelectedItem().toString();
            for(int i = 0; i < theCourseNode.getStudentNodes().getStudentNodeList().size(); i++)
            {
                for(int j=0; j<theCourseNode.getStudentNodes().getStudentNodeList().get(i).getStudent().getProjectList().size(); j++){
                    if(value.equals(theCourseNode.getStudentNodes().getStudentNodeList().get(i).getStudent().getProjectList().get(j).getName())){
                        listModel.addElement(theCourseNode.getStudentNodes().getStudentNodeList().get(i).getStudent().getProjectList().get(j).getName());
                    }    
                }
                
                    
            }
            
            
            
        }
            //repaint();
    }//GEN-LAST:event_AddBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        // TODO add your handling code here:
        //DefaultListModel model = (DefaultListModel) projectRunList.getModel();
        
        int selectedIndex = projectRunList.getSelectedIndex();
        if(selectedIndex < 0){
            JOptionPane.showMessageDialog(null, "Nothing is selected", "Error!", JOptionPane.DEFAULT_OPTION);
        }
        else{
            //int selectedIndex = projectRunList.getSelectedIndex();
            listModel.removeElementAt(selectedIndex);
            repaint();
        }
        
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void RunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBtnActionPerformed
        // TODO add your handling code here:
        if (listModel == null) return;
        else{
            int listLength = listModel.getSize();
            for(int i = 0; i<listLength; i++)
                listToPass.add(listModel.get(i));
        }
        // Method call to back end team's method which will read in listToPass as a parameter
        
    }//GEN-LAST:event_RunBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //repaint();
        this.dispose();
        theMainMenuCntl.updateMainMenuUI();
    }//GEN-LAST:event_backBtnActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton RunBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTree courseTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox projectComboBox;
    private javax.swing.JLabel projectRunLabel;
    private javax.swing.JList projectRunList;
    private javax.swing.JLabel runSetupLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
